= GruntWurk TextDataSimplifier

A command-line tool that converts fixed-field paginated data (a.k.a. "line printer reports") to delimited data -- either comma-separated-values (CSV) or tab-separated (TSV).

An INI file is used to specify how the paginated data is to be interpreted. For example, it declares how many lines at the top of each page make up the page header, likewise for any page footer. It also specifies where the fields of interest start and stop on each line.

Data is then plucked out of the report and written to an output file. Every data "row" in the body of the page (which can be more than one wrapped line) corresponds to one line in the output file. Any data that is plucked from the page header and/or page footer is prepended to each data line as it is written.

Another feature is that if a report file consists of multiple parts, each part can be processed independently. For example, if the first two pages of the report are an introduction and the last five pages are a summary, then the introduction, the main section, and the summary can each be processed separately -- with different sets of specifications -- resulting in three different output files.


== Command-Line Flags

.Command-Line Flags
[width="100%",cols="2,5,5",options="header"]
|===
| Flag | Argument | Meaning
| -f | name of the input file(s) | May include wildcards.
| -o | name of the output file to hold copies of all duplicated records found | If not given, then assumes the same as the input file but with a .OUT extension. Will be overwritten if already exists.
| --verbose | | Displays detailed information (statistics).
| --debug | | Displays how the specification file was interpreted, among other things.
| -l | name of a log file to use | Will be appended to the end if already exists.
| -s | name of the specification file | If not given, then assumes the same as the input file but with a .INI extension.
| --help | | Get help on these flag definitions.
|===

If multiple files are specified (via wildcards), the results will be combined in a single output file.

Redirecting the console output to a log file (`>> some.log`) is functionally equivalent to using the `-l` flag.


== Specification Files

A simple INI file tells TextDataSimplifier how to interpret the input file. It also controls how the tool does its work, and it controls how the findings are reported.

	[File]
	Type=Paginated

	[Output]
	Type=TSV
	Delimiter=\T

	[Part 1]
	Pages = 1..2
	Header Lines = 1..8
	Data Lines = 9..-3
	Lines Per Row = 1
	Footer Lines = -2..n

	[Part 2]
	Pages = 3..n
	Header Lines = 1..4
	Data Lines = 6..n
	Lines Per Row = 2


Lines that begin with a semicolon are ignored as comments.

=== [File] section

The [File] section is required. It generally describes the input file.

.File Section Keywords
[width="100%",cols="2,3,2,8",options="header"]
|===
| Keyword | Possible Values | Required? | Description
| Type    | Paginated       | required  | Currently, TextDataSimplifier only knows how to work with fixed-field and paginated files, so this must be set to `Paginated`.
|===

Other tools in the GruntWurk suite also use INI files for specifications. One purpose of requiring the Type=Paginated line here is to ensure that if an INI file meant for one tool is accidentally sent to another tool, it will stop short as soon as it sees the wrong file type.

=== [Output] section

The [Output] section is required. It describes how the converted data should be expressed.

.File Section Keywords
[width="100%",cols="2,3,2,8",options="header"]
|===
| Keyword | Possible Values | Required? | Description
| Type | CSV or TSV | required | Currently, TextDataSimplifier only knows how to output the converted data as delimited files, so this must be set to `CSV` or `TSV`.
| Delimiter | any one character or the word TAB (or \T) | optional | The delimiter that is used to separate fields in the output file. The default is comma (if the type is CSV), or tab (if the type is TSV).
|===



=== Each [Part n] section

At least one [Part n] section is required where n is a consecutive number starting with 1.

.Part Section Keywords
[width="100%",cols="2,3,2,8",options="header"]
|===
| Keyword       | Possible Values | Required? | Description
| Pages         | (range)         | required  | Which pages make up this part
| Header Lines  | (range)         | required  | Which lines make up the page header
| Data Lines    | (range)         | required  | Which lines make up the page body
| Lines Per Row | (number)        | no        | How many lines per data row. 2 or more means it wraps. (Default is 1)
| Footer Lines  | (range)         | no        | Which lines make up the pager footer (default is none)
|===

A (range) can be a single number (3) or a range with a .. operator (3..6).
The second number must always be equal to or greater than the first.
The second  number can also be the letter n, which means "last" (last page or last line).
A negative number means that many from the end. 
So "-2..n" means from the second-to-the-last to the last.
In other words, the last two.




== See Also

include::DEVELOPER_NOTES.adoc[]

https://github.com/gruntwurk/gruntwurk-core/blob/master/DESIGN_PHILOSOPHY.adoc